Repository dsv-rp/DDS, pull requests merged in 2024-11, with the labels that each got.

#83 DDS-1566 [Select] Add Select Component
  .changeset/fluffy-badgers-talk.md
  icons/dropdown-chevron-down.svg
  src/components/index.ts
  src/components/input-group/daikin-input-group.ts
  src/components/input-group/daikin-input-group.visual.test.ts
  src/components/input-group/daikin-input-group.visual.test.ts-snapshots/Select-disabled-optional-error.png
  src/components/input-group/daikin-input-group.visual.test.ts-snapshots/Select-disabled-optional-normal.png
  src/components/input-group/daikin-input-group.visual.test.ts-snapshots/Select-disabled-required-error.png
  src/components/input-group/daikin-input-group.visual.test.ts-snapshots/Select-disabled-required-normal.png
  src/components/input-group/daikin-input-group.visual.test.ts-snapshots/Select-enabled-optional-error.png
  src/components/input-group/daikin-input-group.visual.test.ts-snapshots/Select-enabled-optional-normal.png
  src/components/input-group/daikin-input-group.visual.test.ts-snapshots/Select-enabled-required-error.png
  src/components/input-group/daikin-input-group.visual.test.ts-snapshots/Select-enabled-required-normal.png
  src/components/input-group/stories/common.ts
  src/components/input-group/stories/daikin-input-group.stories.ts
  src/components/input-group/stories/framework-react.tsx
  src/components/input-group/stories/framework-wc.ts
  src/components/select/daikin-select.ts
  src/components/select/daikin-select.visual.test.ts
  src/components/select/daikin-select.visual.test.ts-snapshots/error-active-1.png
  src/components/select/daikin-select.visual.test.ts-snapshots/error-base-1.png
  src/components/select/daikin-select.visual.test.ts-snapshots/error-disabled-1.png
  src/components/select/daikin-select.visual.test.ts-snapshots/error-focus-1.png
  src/components/select/daikin-select.visual.test.ts-snapshots/error-hover-1.png
  src/components/select/daikin-select.visual.test.ts-snapshots/normal-active-1.png
  src/components/select/daikin-select.visual.test.ts-snapshots/normal-base-1.png
  src/components/select/daikin-select.visual.test.ts-snapshots/normal-disabled-1.png
  src/components/select/daikin-select.visual.test.ts-snapshots/normal-focus-1.png
  src/components/select/daikin-select.visual.test.ts-snapshots/normal-hover-1.png
  src/components/select/index.ts
  src/components/select/stories/common.ts
  src/components/select/stories/daikin-select.stories.ts
  src/components/select/stories/framework-react.tsx
  src/components/select/stories/framework-wc.ts
  tailwind.config.cjs
Labels: new component

#80 DDS-1430 [Tabs] Update Appearance
  .changeset/clever-rice-stare.md
  src/colorToken.json
  src/components/tab-panels/daikin-tab-panels.ts
  src/components/tab/daikin-tab.ts
  src/components/tab/daikin-tab.visual.test.ts-snapshots/active-base-1.png
  src/components/tab/daikin-tab.visual.test.ts-snapshots/active-disabled-1.png
  src/components/tab/daikin-tab.visual.test.ts-snapshots/active-focus-1.png
  src/components/tab/daikin-tab.visual.test.ts-snapshots/active-hover-1.png
  src/components/tab/daikin-tab.visual.test.ts-snapshots/active-press-1.png
  src/components/tab/daikin-tab.visual.test.ts-snapshots/normal-base-1.png
  src/components/tab/daikin-tab.visual.test.ts-snapshots/normal-disabled-1.png
  src/components/tab/daikin-tab.visual.test.ts-snapshots/normal-focus-1.png
  src/components/tab/daikin-tab.visual.test.ts-snapshots/normal-hover-1.png
  src/components/tab/daikin-tab.visual.test.ts-snapshots/normal-press-1.png
  src/components/tabs/daikin-tabs.ts
  src/components/tabs/daikin-tabs.visual.test.ts
  src/components/tabs/daikin-tabs.visual.test.ts-snapshots/default-baz-base-1.png
  src/components/tabs/daikin-tabs.visual.test.ts-snapshots/default-foo-base-1.png
  src/components/tabs/daikin-tabs.visual.test.ts-snapshots/many-tab1-base-1.png
  src/components/tabs/daikin-tabs.visual.test.ts-snapshots/many-tab10-base-1.png
  src/components/tabs/daikin-tabs.visual.test.ts-snapshots/many-tab20-base-1.png
  src/components/tabs/daikin-tabs.visual.test.ts-snapshots/scrollable-tab1-base-1.png
  src/components/tabs/daikin-tabs.visual.test.ts-snapshots/scrollable-tab10-base-1.png
  src/components/tabs/daikin-tabs.visual.test.ts-snapshots/scrollable-tab20-base-1.png
  src/components/tabs/daikin-tabs.visual.test.ts-snapshots/single-foo-base-1.png
  src/components/tabs/stories/common.ts
  src/components/tabs/stories/daikin-tabs.stories.ts
  src/components/tabs/stories/framework-react.tsx
  src/components/tabs/stories/framework-wc.ts
Labels: retouching

#65 DDS-1361 [Radio Group] Add radio group component
  .changeset/cold-phones-lie.md
  cspell-dictionary.txt
  src/components/checkbox/daikin-checkbox.ts
  src/components/dropdown/daikin-dropdown.ts
  src/components/input-group/daikin-input-group.ts
  src/components/radio-group/daikin-radio-group.ts
  src/components/radio-group/daikin-radio-group.visual.test.ts
  src/components/radio-group/daikin-radio-group.visual.test.ts-snapshots/horizontal-base-1.png
  src/components/radio-group/daikin-radio-group.visual.test.ts-snapshots/vertical-base-1.png
  src/components/radio-group/index.ts
  src/components/radio-group/stories/common.ts
  src/components/radio-group/stories/daikin-radio-group.stories.ts
  src/components/radio-group/stories/framework-react.tsx
  src/components/radio-group/stories/framework-wc.ts
  src/components/radio/daikin-radio.ts
  src/components/radio/stories/framework-react.tsx
  src/components/select/daikin-select.ts
  src/components/text-area/daikin-text-area.ts
  src/components/text-field/daikin-text-field.ts
Labels: new component, waiting for design

#47 DDS-921 [Progress Indicator] Add Progress Indicator Component
  .changeset/thin-roses-drum.md
  icons/notification-status-positive.svg
  icons/status-alarm.svg
  icons/status-information.svg
  icons/status-negative.svg
  icons/status-positive.svg
  icons/status-success.svg
  icons/status-warning.svg
  src/components/icon/icons.json
  src/components/index.ts
  src/components/progress-bar/daikin-progress-bar.ts
  src/components/progress-indicator-item/daikin-progress-indicator-item.ts
  src/components/progress-indicator-item/daikin-progress-indicator-item.visual.test.ts
  src/components/progress-indicator-item/daikin-progress-indicator-item.visual.test.ts-snapshots/finished-base-1.png
  src/components/progress-indicator-item/daikin-progress-indicator-item.visual.test.ts-snapshots/inprogress-base-1.png
  src/components/progress-indicator-item/daikin-progress-indicator-item.visual.test.ts-snapshots/unfinished-base-1.png
  src/components/progress-indicator-item/index.ts
  src/components/progress-indicator-item/stories/common.ts
  src/components/progress-indicator-item/stories/daikin-progress-indicator-item.stories.ts
  src/components/progress-indicator-item/stories/framework-react.tsx
  src/components/progress-indicator-item/stories/framework-wc.ts
  src/components/progress-indicator/daikin-progress-indicator.ts
  src/components/progress-indicator/daikin-progress-indicator.visual.test.ts
  src/components/progress-indicator/daikin-progress-indicator.visual.test.ts-snapshots/base-1.png
  src/components/progress-indicator/index.ts
  src/components/progress-indicator/stories/common.ts
  src/components/progress-indicator/stories/daikin-progress-indicator.stories.ts
  src/components/progress-indicator/stories/framework-react.tsx
  src/components/progress-indicator/stories/framework-wc.ts
Labels: new component, waiting for design

#96 Fix the appearance of the accordion
  .changeset/dull-mirrors-begin.md
  src/components/accordion-item/daikin-accordion-item.ts
Labels: bug

#97 [Progress Indicator] Screen reader support
  src/components/progress-indicator-item/daikin-progress-indicator-item.ts
Labels: retouching

#95 DDS-1631 [Tooltip] Fix Tooltip Remaining After Click
  .changeset/brown-boxes-sip.md
  cspell-dictionary.txt
  src/components/dropdown/daikin-dropdown.ts
  src/components/tooltip/daikin-tooltip.ts
  src/components/tooltip/stories/daikin-tooltip.stories.ts
  src/controllers/floating-ui-auto-update.ts
  src/tailwind.css
Labels: bug

#93 DDS-1600 [Link] Add Link Component
  .changeset/seven-pants-kick.md
  color-tokens.json
  src/components/index.ts
  src/components/link/daikin-link.ts
  src/components/link/daikin-link.visual.test.ts
  src/components/link/daikin-link.visual.test.ts-snapshots/left-base-1.png
  src/components/link/daikin-link.visual.test.ts-snapshots/left-disabled-1.png
  src/components/link/daikin-link.visual.test.ts-snapshots/left-focus-1.png
  src/components/link/daikin-link.visual.test.ts-snapshots/left-hover-1.png
  src/components/link/daikin-link.visual.test.ts-snapshots/left-press-1.png
  src/components/link/daikin-link.visual.test.ts-snapshots/none-base-1.png
  src/components/link/daikin-link.visual.test.ts-snapshots/none-disabled-1.png
  src/components/link/daikin-link.visual.test.ts-snapshots/none-focus-1.png
  src/components/link/daikin-link.visual.test.ts-snapshots/none-hover-1.png
  src/components/link/daikin-link.visual.test.ts-snapshots/none-press-1.png
  src/components/link/daikin-link.visual.test.ts-snapshots/right-base-1.png
  src/components/link/daikin-link.visual.test.ts-snapshots/right-disabled-1.png
  src/components/link/daikin-link.visual.test.ts-snapshots/right-focus-1.png
  src/components/link/daikin-link.visual.test.ts-snapshots/right-hover-1.png
  src/components/link/daikin-link.visual.test.ts-snapshots/right-press-1.png
  src/components/link/index.ts
  src/components/link/stories/common.ts
  src/components/link/stories/daikin-link.stories.ts
  src/components/link/stories/framework-react.tsx
  src/components/link/stories/framework-wc.ts
Labels: new component

#79 DDS-1529 Correct Package Type Definitions
  .changeset/orange-baboons-help.md
  .github/workflows/test.yml
  .gitignore
  build/vite/dts-with-fix/index.ts
  build/vite/storybook-framework-loader/index.ts
  cspell-dictionary.txt
  package-lock.json
  package.json
  vite.config.ts
Labels: bug, build

#53 DDS-1355 DDS-1429 Add ESLint rules, Rename/remove some Attributes
  .changeset/soft-tomatoes-double.md
  .ls-lint.yml
  cspell-dictionary.txt
  cspell.json
  eslint.config.js
  package-lock.json
  package.json
  src/colorToken.json
  src/components/accordion-item/daikin-accordion-item.ts
  src/components/breadcrumb-item/daikin-breadcrumb-item.ts
  src/components/checkbox/daikin-checkbox.ts
  src/components/input-group/stories/common.ts
  src/components/notification/daikin-notification.ts
  src/components/notification/stories/framework-wc.ts
  src/components/pagination/stories/daikin-pagination.stories.ts
  src/components/progress-indicator-item/stories/common.ts
  src/components/progress-indicator/stories/common.ts
  src/components/radio-group/stories/daikin-radio-group.stories.ts
  src/components/radio/daikin-radio.ts
  src/components/tab-panels/stories/common.ts
  src/components/text-area/daikin-text-area.ts
  src/components/text-area/stories/common.ts
  src/components/text-field/daikin-text-field.ts
  src/components/text-field/stories/common.ts
  src/components/text-field/stories/framework-wc.ts
  src/components/toggle/daikin-toggle.ts
  src/components/tooltip/daikin-tooltip.ts
  src/require-package.unit.test.cts
  src/utils/re-dispatch.ts
  tsconfig.lib.json
Labels: build
