Repository dsv-rp/DDS, pull requests merged in 2024-09, with the labels that each got.

#50 DDS-1320 [Notification] Support using Slots for Title and Description
  .changeset/old-clouds-type.md
  src/components/notification/daikin-notification.ts
  src/components/notification/daikin-notification.visual.test.ts
  src/components/notification/daikin-notification.visual.test.ts-snapshots/inline-alarm-multi-withClose-base-1.png
  src/components/notification/daikin-notification.visual.test.ts-snapshots/inline-alarm-multi-withoutClose-base-1.png
  src/components/notification/daikin-notification.visual.test.ts-snapshots/inline-alarm-single-withClose-base-1.png
  src/components/notification/daikin-notification.visual.test.ts-snapshots/inline-alarm-single-withoutClose-base-1.png
  src/components/notification/daikin-notification.visual.test.ts-snapshots/inline-information-multi-withClose-base-1.png
  src/components/notification/daikin-notification.visual.test.ts-snapshots/inline-information-multi-withoutClose-base-1.png
  src/components/notification/daikin-notification.visual.test.ts-snapshots/inline-information-single-withClose-base-1.png
  src/components/notification/daikin-notification.visual.test.ts-snapshots/inline-information-single-withoutClose-base-1.png
  src/components/notification/daikin-notification.visual.test.ts-snapshots/inline-negative-multi-withClose-base-1.png
  src/components/notification/daikin-notification.visual.test.ts-snapshots/inline-negative-multi-withoutClose-base-1.png
  src/components/notification/daikin-notification.visual.test.ts-snapshots/inline-negative-single-withClose-base-1.png
  src/components/notification/daikin-notification.visual.test.ts-snapshots/inline-negative-single-withoutClose-base-1.png
  src/components/notification/daikin-notification.visual.test.ts-snapshots/inline-positive-multi-withClose-base-1.png
  src/components/notification/daikin-notification.visual.test.ts-snapshots/inline-positive-multi-withoutClose-base-1.png
  src/components/notification/daikin-notification.visual.test.ts-snapshots/inline-positive-single-withClose-base-1.png
  src/components/notification/daikin-notification.visual.test.ts-snapshots/inline-positive-single-withoutClose-base-1.png
  src/components/notification/daikin-notification.visual.test.ts-snapshots/inline-warning-multi-withClose-base-1.png
  src/components/notification/daikin-notification.visual.test.ts-snapshots/inline-warning-multi-withoutClose-base-1.png
  src/components/notification/daikin-notification.visual.test.ts-snapshots/inline-warning-single-withClose-base-1.png
  src/components/notification/daikin-notification.visual.test.ts-snapshots/inline-warning-single-withoutClose-base-1.png
  src/components/notification/daikin-notification.visual.test.ts-snapshots/toast-alarm-multi-withClose-base-1.png
  src/components/notification/daikin-notification.visual.test.ts-snapshots/toast-alarm-multi-withoutClose-base-1.png
  src/components/notification/daikin-notification.visual.test.ts-snapshots/toast-alarm-single-withClose-base-1.png
  src/components/notification/daikin-notification.visual.test.ts-snapshots/toast-alarm-single-withoutClose-base-1.png
  src/components/notification/daikin-notification.visual.test.ts-snapshots/toast-information-multi-withClose-base-1.png
  src/components/notification/daikin-notification.visual.test.ts-snapshots/toast-information-multi-withoutClose-base-1.png
  src/components/notification/daikin-notification.visual.test.ts-snapshots/toast-information-single-withClose-base-1.png
  src/components/notification/daikin-notification.visual.test.ts-snapshots/toast-information-single-withoutClose-base-1.png
  src/components/notification/daikin-notification.visual.test.ts-snapshots/toast-negative-multi-withClose-base-1.png
  src/components/notification/daikin-notification.visual.test.ts-snapshots/toast-negative-multi-withoutClose-base-1.png
  src/components/notification/daikin-notification.visual.test.ts-snapshots/toast-negative-single-withClose-base-1.png
  src/components/notification/daikin-notification.visual.test.ts-snapshots/toast-negative-single-withoutClose-base-1.png
  src/components/notification/daikin-notification.visual.test.ts-snapshots/toast-positive-multi-withClose-base-1.png
  src/components/notification/daikin-notification.visual.test.ts-snapshots/toast-positive-multi-withoutClose-base-1.png
  src/components/notification/daikin-notification.visual.test.ts-snapshots/toast-positive-single-withClose-base-1.png
  src/components/notification/daikin-notification.visual.test.ts-snapshots/toast-positive-single-withoutClose-base-1.png
  src/components/notification/daikin-notification.visual.test.ts-snapshots/toast-warning-multi-withClose-base-1.png
  src/components/notification/daikin-notification.visual.test.ts-snapshots/toast-warning-multi-withoutClose-base-1.png
  src/components/notification/daikin-notification.visual.test.ts-snapshots/toast-warning-single-withClose-base-1.png
  src/components/notification/daikin-notification.visual.test.ts-snapshots/toast-warning-single-withoutClose-base-1.png
  src/components/notification/stories/common.ts
  src/components/notification/stories/daikin-notification.stories.ts
  src/components/notification/stories/framework-react.tsx
  src/components/notification/stories/framework-wc.ts
Labels: enhancement

#59 DDS-1440 DDS-1445 [Storybook] Improve the code displayed by "Show code"
  .changeset/old-zoos-learn.md
  .storybook/main-common.ts
  build/vite/storybook-framework-loader/description.ts
  build/vite/storybook-framework-loader/index.ts
  build/vite/storybook-framework-loader/wca.ts
  cspell-dictionary.txt
  package-lock.json
  package.json
  src/components/icon/stories/framework-wc.ts
  src/storybook/fix-code.ts
  src/storybook/fix-code.unit.test.ts
  src/storybook/index.ts
  vite.config.storybook.ts
Labels: enhancement, build

#63 DDS-1374 [Toggle] Retouching
  .changeset/weak-donkeys-flow.md
  src/components/toggle/daikin-toggle.ts
  src/components/toggle/daikin-toggle.visual.test.ts
  src/components/toggle/daikin-toggle.visual.test.ts-snapshots/checked-base-1.png
  src/components/toggle/daikin-toggle.visual.test.ts-snapshots/checked-disabled-1.png
  src/components/toggle/daikin-toggle.visual.test.ts-snapshots/checked-focus-1.png
  src/components/toggle/daikin-toggle.visual.test.ts-snapshots/checked-hover-1.png
  src/components/toggle/daikin-toggle.visual.test.ts-snapshots/checked-press-1.png
  src/components/toggle/daikin-toggle.visual.test.ts-snapshots/disabled-default-checked-base-1.png
  src/components/toggle/daikin-toggle.visual.test.ts-snapshots/disabled-default-unchecked-base-1.png
  src/components/toggle/daikin-toggle.visual.test.ts-snapshots/disabled-small-checked-base-1.png
  src/components/toggle/daikin-toggle.visual.test.ts-snapshots/disabled-small-unchecked-base-1.png
  src/components/toggle/daikin-toggle.visual.test.ts-snapshots/enabled-default-checked-base-1.png
  src/components/toggle/daikin-toggle.visual.test.ts-snapshots/enabled-default-unchecked-base-1.png
  src/components/toggle/daikin-toggle.visual.test.ts-snapshots/enabled-small-checked-base-1.png
  src/components/toggle/daikin-toggle.visual.test.ts-snapshots/enabled-small-unchecked-base-1.png
  src/components/toggle/daikin-toggle.visual.test.ts-snapshots/unchecked-base-1.png
  src/components/toggle/daikin-toggle.visual.test.ts-snapshots/unchecked-disabled-1.png
  src/components/toggle/daikin-toggle.visual.test.ts-snapshots/unchecked-focus-1.png
  src/components/toggle/daikin-toggle.visual.test.ts-snapshots/unchecked-hover-1.png
  src/components/toggle/daikin-toggle.visual.test.ts-snapshots/unchecked-press-1.png
  src/components/toggle/stories/common.ts
  src/components/toggle/stories/daikin-toggle.stories.ts
  src/components/toggle/stories/framework-wc.ts
Labels: retouching
