Repository dsv-rp/DDS, pull requests merged in 2024-12, with the labels that each got.

#73 DDS-1299 [Tree] Add Tree Component
  .changeset/proud-rules-give.md
  cspell-dictionary.txt
  package.json
  src/components/button/daikin-button.ts
  src/components/index.ts
  src/components/tree-item/daikin-tree-item.ts
  src/components/tree-item/daikin-tree-item.visual.test.ts
  src/components/tree-item/daikin-tree-item.visual.test.ts-snapshots/normal-base-1.png
  src/components/tree-item/daikin-tree-item.visual.test.ts-snapshots/normal-disabled-1.png
  src/components/tree-item/daikin-tree-item.visual.test.ts-snapshots/normal-focus-1.png
  src/components/tree-item/daikin-tree-item.visual.test.ts-snapshots/normal-hover-1.png
  src/components/tree-item/daikin-tree-item.visual.test.ts-snapshots/normal-press-1.png
  src/components/tree-item/daikin-tree-item.visual.test.ts-snapshots/selected-base-1.png
  src/components/tree-item/daikin-tree-item.visual.test.ts-snapshots/selected-disabled-1.png
  src/components/tree-item/daikin-tree-item.visual.test.ts-snapshots/selected-focus-1.png
  src/components/tree-item/daikin-tree-item.visual.test.ts-snapshots/selected-hover-1.png
  src/components/tree-item/daikin-tree-item.visual.test.ts-snapshots/selected-press-1.png
  src/components/tree-item/index.ts
  src/components/tree-item/stories/common.ts
  src/components/tree-item/stories/daikin-tree-item.stories.ts
  src/components/tree-item/stories/framework-react.tsx
  src/components/tree-item/stories/framework-wc.ts
  src/components/tree-section/daikin-tree-section.ts
  src/components/tree-section/daikin-tree-section.visual.test.ts
  src/components/tree-section/daikin-tree-section.visual.test.ts-snapshots/normal-disabled-close-base-1.png
  src/components/tree-section/daikin-tree-section.visual.test.ts-snapshots/normal-disabled-open-base-1.png
  src/components/tree-section/daikin-tree-section.visual.test.ts-snapshots/normal-enabled-close-base-1.png
  src/components/tree-section/daikin-tree-section.visual.test.ts-snapshots/normal-enabled-open-base-1.png
  src/components/tree-section/daikin-tree-section.visual.test.ts-snapshots/selected-disabled-close-base-1.png
  src/components/tree-section/daikin-tree-section.visual.test.ts-snapshots/selected-disabled-open-base-1.png
  src/components/tree-section/daikin-tree-section.visual.test.ts-snapshots/selected-enabled-close-base-1.png
  src/components/tree-section/daikin-tree-section.visual.test.ts-snapshots/selected-enabled-open-base-1.png
  src/components/tree-section/index.ts
  src/components/tree-section/stories/common.ts
  src/components/tree-section/stories/daikin-tree-section.stories.ts
  src/components/tree-section/stories/framework-react.tsx
  src/components/tree-section/stories/framework-wc.ts
  src/components/tree/common.ts
  src/components/tree/daikin-tree.ts
  src/components/tree/daikin-tree.visual.test.ts
  src/components/tree/daikin-tree.visual.test.ts-snapshots/normal-base-1.png
  src/components/tree/daikin-tree.visual.test.ts-snapshots/selectable-base-1.png
  src/components/tree/index.ts
  src/components/tree/stories/common.ts
  src/components/tree/stories/daikin-tree.stories.ts
  src/components/tree/stories/framework-react.tsx
  src/components/tree/stories/framework-wc.ts
  src/utils/is-simple-key.ts
  tailwind.config.cjs
Labels: new component

#105 DDS-1513 Integrate Design Tokens (1/3: Base Integration)
  .changeset/loud-squids-carry.md
  .storybook/docs.css
  .storybook/preview-common.ts
  .storybook/preview.tsx
  .storybook/react/preview.tsx
  .storybook/theme.scss
  README.md
  build/eslint/index.ts
  build/eslint/rules/ban-missing-design-tokens.ts
  build/eslint/rules/index.ts
  build/tailwindcss/icons.ts
  build/tailwindcss/index.ts
  build/tailwindcss/temporary-color-tokens.json
  build/tailwindcss/tokens.ts
  build/tailwindcss/utils.ts
  cspell-dictionary.txt
  cspell.json
  eslint.config.js
  package-lock.json
  package.json
  src/colors.ts
  src/components/icon/daikin-icon.ts
  src/components/input-group/daikin-input-group.ts
  src/components/link/daikin-link.ts
  src/components/link/daikin-link.visual.test.ts-snapshots/left-press-1.png
  src/components/link/daikin-link.visual.test.ts-snapshots/none-press-1.png
  src/components/link/daikin-link.visual.test.ts-snapshots/right-press-1.png
  src/components/notification/daikin-notification.ts
  src/components/progress-indicator/daikin-progress-indicator.ts
  src/components/tooltip/daikin-tooltip.ts
  src/import-path.unit.test.ts
  src/index.ts
  src/require-package.unit.test.cts
  src/storybook/define-play.ts
  src/tests/visual/runner.ts
  src/tests/visual/storybook-iframe-url.ts
  tailwind.config.cjs
  vite.config.storybook.ts
Labels: build

#104 DDS-1295 [Breadcrumb] Retouching
  .changeset/long-cats-visit.md
  src/components/breadcrumb-item/daikin-breadcrumb-item.ts
  src/components/breadcrumb-item/daikin-breadcrumb-item.visual.test.ts
  src/components/breadcrumb-item/daikin-breadcrumb-item.visual.test.ts-snapshots/current-base-1.png
  src/components/breadcrumb-item/daikin-breadcrumb-item.visual.test.ts-snapshots/disabled-ellipsis-noTrailingSlash-base-1.png
  src/components/breadcrumb-item/daikin-breadcrumb-item.visual.test.ts-snapshots/disabled-ellipsis-noTrailingSlash-focus-1.png
  src/components/breadcrumb-item/daikin-breadcrumb-item.visual.test.ts-snapshots/disabled-ellipsis-noTrailingSlash-hover-1.png
  src/components/breadcrumb-item/daikin-breadcrumb-item.visual.test.ts-snapshots/disabled-ellipsis-noTrailingSlash-press-1.png
  src/components/breadcrumb-item/daikin-breadcrumb-item.visual.test.ts-snapshots/disabled-ellipsis-trailingSlash-base-1.png
  src/components/breadcrumb-item/daikin-breadcrumb-item.visual.test.ts-snapshots/disabled-ellipsis-trailingSlash-focus-1.png
  src/components/breadcrumb-item/daikin-breadcrumb-item.visual.test.ts-snapshots/disabled-ellipsis-trailingSlash-hover-1.png
  src/components/breadcrumb-item/daikin-breadcrumb-item.visual.test.ts-snapshots/disabled-ellipsis-trailingSlash-press-1.png
  src/components/breadcrumb-item/daikin-breadcrumb-item.visual.test.ts-snapshots/disabled-normal-noTrailingSlash-base-1.png
  src/components/breadcrumb-item/daikin-breadcrumb-item.visual.test.ts-snapshots/disabled-normal-noTrailingSlash-focus-1.png
  src/components/breadcrumb-item/daikin-breadcrumb-item.visual.test.ts-snapshots/disabled-normal-noTrailingSlash-hover-1.png
  src/components/breadcrumb-item/daikin-breadcrumb-item.visual.test.ts-snapshots/disabled-normal-noTrailingSlash-press-1.png
  src/components/breadcrumb-item/daikin-breadcrumb-item.visual.test.ts-snapshots/disabled-normal-trailingSlash-base-1.png
  src/components/breadcrumb-item/daikin-breadcrumb-item.visual.test.ts-snapshots/disabled-normal-trailingSlash-focus-1.png
  src/components/breadcrumb-item/daikin-breadcrumb-item.visual.test.ts-snapshots/disabled-normal-trailingSlash-hover-1.png
  src/components/breadcrumb-item/daikin-breadcrumb-item.visual.test.ts-snapshots/disabled-normal-trailingSlash-press-1.png
  src/components/breadcrumb-item/daikin-breadcrumb-item.visual.test.ts-snapshots/enabled-ellipsis-noTrailingSlash-base-1.png
  src/components/breadcrumb-item/daikin-breadcrumb-item.visual.test.ts-snapshots/enabled-ellipsis-noTrailingSlash-focus-1.png
  src/components/breadcrumb-item/daikin-breadcrumb-item.visual.test.ts-snapshots/enabled-ellipsis-noTrailingSlash-hover-1.png
  src/components/breadcrumb-item/daikin-breadcrumb-item.visual.test.ts-snapshots/enabled-ellipsis-noTrailingSlash-press-1.png
  src/components/breadcrumb-item/daikin-breadcrumb-item.visual.test.ts-snapshots/enabled-ellipsis-trailingSlash-base-1.png
  src/components/breadcrumb-item/daikin-breadcrumb-item.visual.test.ts-snapshots/enabled-ellipsis-trailingSlash-focus-1.png
  src/components/breadcrumb-item/daikin-breadcrumb-item.visual.test.ts-snapshots/enabled-ellipsis-trailingSlash-hover-1.png
  src/components/breadcrumb-item/daikin-breadcrumb-item.visual.test.ts-snapshots/enabled-ellipsis-trailingSlash-press-1.png
  src/components/breadcrumb-item/daikin-breadcrumb-item.visual.test.ts-snapshots/enabled-normal-noTrailingSlash-base-1.png
  src/components/breadcrumb-item/daikin-breadcrumb-item.visual.test.ts-snapshots/enabled-normal-noTrailingSlash-focus-1.png
  src/components/breadcrumb-item/daikin-breadcrumb-item.visual.test.ts-snapshots/enabled-normal-noTrailingSlash-hover-1.png
  src/components/breadcrumb-item/daikin-breadcrumb-item.visual.test.ts-snapshots/enabled-normal-noTrailingSlash-press-1.png
  src/components/breadcrumb-item/daikin-breadcrumb-item.visual.test.ts-snapshots/enabled-normal-trailingSlash-base-1.png
  src/components/breadcrumb-item/daikin-breadcrumb-item.visual.test.ts-snapshots/enabled-normal-trailingSlash-focus-1.png
  src/components/breadcrumb-item/daikin-breadcrumb-item.visual.test.ts-snapshots/enabled-normal-trailingSlash-hover-1.png
  src/components/breadcrumb-item/daikin-breadcrumb-item.visual.test.ts-snapshots/enabled-normal-trailingSlash-press-1.png
  src/components/breadcrumb-item/daikin-breadcrumb-item.visual.test.ts-snapshots/normal-base-1.png
  src/components/breadcrumb-item/daikin-breadcrumb-item.visual.test.ts-snapshots/normal-focus-1.png
  src/components/breadcrumb-item/daikin-breadcrumb-item.visual.test.ts-snapshots/normal-hover-1.png
  src/components/breadcrumb-item/daikin-breadcrumb-item.visual.test.ts-snapshots/normal-press-1.png
  src/components/breadcrumb-item/stories/common.ts
  src/components/breadcrumb-item/stories/daikin-breadcrumb-item.stories.ts
  src/components/breadcrumb-item/stories/framework-react.tsx
  src/components/breadcrumb-item/stories/framework-wc.ts
  src/components/breadcrumb/daikin-breadcrumb.ts
  src/components/breadcrumb/daikin-breadcrumb.visual.test.ts
  src/components/breadcrumb/daikin-breadcrumb.visual.test.ts-snapshots/base-1.png
  src/components/breadcrumb/daikin-breadcrumb.visual.test.ts-snapshots/noTrailingSlash-ellipsis-base-1.png
  src/components/breadcrumb/daikin-breadcrumb.visual.test.ts-snapshots/noTrailingSlash-ellipsis-smallScreen-1.png
  src/components/breadcrumb/daikin-breadcrumb.visual.test.ts-snapshots/noTrailingSlash-visible-base-1.png
  src/components/breadcrumb/daikin-breadcrumb.visual.test.ts-snapshots/noTrailingSlash-visible-smallScreen-1.png
  src/components/breadcrumb/daikin-breadcrumb.visual.test.ts-snapshots/trailingSlash-ellipsis-base-1.png
  src/components/breadcrumb/daikin-breadcrumb.visual.test.ts-snapshots/trailingSlash-ellipsis-smallScreen-1.png
  src/components/breadcrumb/daikin-breadcrumb.visual.test.ts-snapshots/trailingSlash-visible-base-1.png
  src/components/breadcrumb/daikin-breadcrumb.visual.test.ts-snapshots/trailingSlash-visible-smallScreen-1.png
  src/components/breadcrumb/stories/common.ts
  src/components/breadcrumb/stories/daikin-breadcrumb.stories.ts
  src/components/breadcrumb/stories/framework-react.tsx
  src/components/breadcrumb/stories/framework-wc.ts
Labels: retouching

#111 DDS-1209 [Card] Add Card Component
  .changeset/calm-apes-allow.md
  src/components/card-footer/daikin-card-footer.ts
  src/components/card-footer/daikin-card-footer.visual.test.ts
  src/components/card-footer/daikin-card-footer.visual.test.ts-snapshots/dark-button-base-1.png
  src/components/card-footer/daikin-card-footer.visual.test.ts-snapshots/dark-link-base-1.png
  src/components/card-footer/daikin-card-footer.visual.test.ts-snapshots/light-button-base-1.png
  src/components/card-footer/daikin-card-footer.visual.test.ts-snapshots/light-link-base-1.png
  src/components/card-footer/index.ts
  src/components/card-footer/stories/common.ts
  src/components/card-footer/stories/daikin-card-footer.stories.ts
  src/components/card-footer/stories/framework-react.tsx
  src/components/card-footer/stories/framework-wc.ts
  src/components/card-header/daikin-card-header.ts
  src/components/card-header/daikin-card-header.visual.test.ts
  src/components/card-header/daikin-card-header.visual.test.ts-snapshots/dark-both-base-1.png
  src/components/card-header/daikin-card-header.visual.test.ts-snapshots/dark-description-base-1.png
  src/components/card-header/daikin-card-header.visual.test.ts-snapshots/dark-icon-base-1.png
  src/components/card-header/daikin-card-header.visual.test.ts-snapshots/light-both-base-1.png
  src/components/card-header/daikin-card-header.visual.test.ts-snapshots/light-description-base-1.png
  src/components/card-header/daikin-card-header.visual.test.ts-snapshots/light-icon-base-1.png
  src/components/card-header/index.ts
  src/components/card-header/stories/common.ts
  src/components/card-header/stories/daikin-card-header.stories.ts
  src/components/card-header/stories/framework-react.tsx
  src/components/card-header/stories/framework-wc.ts
  src/components/card/daikin-card.ts
  src/components/card/daikin-card.visual.test.ts
  src/components/card/daikin-card.visual.test.ts-snapshots/dark-ghost-body-base-1.png
  src/components/card/daikin-card.visual.test.ts-snapshots/dark-ghost-both-base-1.png
  src/components/card/daikin-card.visual.test.ts-snapshots/dark-ghost-footer-base-1.png
  src/components/card/daikin-card.visual.test.ts-snapshots/dark-outline-body-base-1.png
  src/components/card/daikin-card.visual.test.ts-snapshots/dark-outline-both-base-1.png
  src/components/card/daikin-card.visual.test.ts-snapshots/dark-outline-footer-base-1.png
  src/components/card/daikin-card.visual.test.ts-snapshots/light-ghost-body-base-1.png
  src/components/card/daikin-card.visual.test.ts-snapshots/light-ghost-both-base-1.png
  src/components/card/daikin-card.visual.test.ts-snapshots/light-ghost-footer-base-1.png
  src/components/card/daikin-card.visual.test.ts-snapshots/light-outline-body-base-1.png
  src/components/card/daikin-card.visual.test.ts-snapshots/light-outline-both-base-1.png
  src/components/card/daikin-card.visual.test.ts-snapshots/light-outline-footer-base-1.png
  src/components/card/index.ts
  src/components/card/stories/common.ts
  src/components/card/stories/daikin-card.stories.ts
  src/components/card/stories/framework-react.tsx
  src/components/card/stories/framework-wc.ts
  src/components/index.ts
Labels: new component

#100 DDS-1302 [Progress Indicator] Retouching
  .changeset/cool-pugs-act.md
  src/components/progress-indicator-item/daikin-progress-indicator-item.ts
  src/components/progress-indicator-item/daikin-progress-indicator-item.visual.test.ts-snapshots/dark-finished-base-1.png
  src/components/progress-indicator-item/daikin-progress-indicator-item.visual.test.ts-snapshots/dark-inprogress-base-1.png
  src/components/progress-indicator-item/daikin-progress-indicator-item.visual.test.ts-snapshots/dark-unfinished-base-1.png
  src/components/progress-indicator-item/daikin-progress-indicator-item.visual.test.ts-snapshots/finished-base-1.png
  src/components/progress-indicator-item/daikin-progress-indicator-item.visual.test.ts-snapshots/inprogress-base-1.png
  src/components/progress-indicator-item/daikin-progress-indicator-item.visual.test.ts-snapshots/light-finished-base-1.png
  src/components/progress-indicator-item/daikin-progress-indicator-item.visual.test.ts-snapshots/light-inprogress-base-1.png
  src/components/progress-indicator-item/daikin-progress-indicator-item.visual.test.ts-snapshots/light-unfinished-base-1.png
  src/components/progress-indicator-item/daikin-progress-indicator-item.visual.test.ts-snapshots/unfinished-base-1.png
  src/components/progress-indicator/daikin-progress-indicator.ts
  src/components/progress-indicator/daikin-progress-indicator.visual.test.ts-snapshots/base-1.png
  src/components/progress-indicator/daikin-progress-indicator.visual.test.ts-snapshots/dark-base-1.png
  src/components/progress-indicator/daikin-progress-indicator.visual.test.ts-snapshots/light-base-1.png
Labels: retouching

#99 [Progress Bar] [Input Group] Update icon
  .changeset/spotty-poets-design.md
  icons/status-error.svg
  src/components/input-group/daikin-input-group.visual.test.ts-snapshots/dark-Dropdown-enabled-optional-error.png
  src/components/input-group/daikin-input-group.visual.test.ts-snapshots/dark-Dropdown-enabled-required-error.png
  src/components/input-group/daikin-input-group.visual.test.ts-snapshots/dark-RadioGroup-enabled-optional-error.png
  src/components/input-group/daikin-input-group.visual.test.ts-snapshots/dark-RadioGroup-enabled-required-error.png
  src/components/input-group/daikin-input-group.visual.test.ts-snapshots/dark-Select-enabled-optional-error.png
  src/components/input-group/daikin-input-group.visual.test.ts-snapshots/dark-Select-enabled-required-error.png
  src/components/input-group/daikin-input-group.visual.test.ts-snapshots/dark-TextArea-enabled-optional-error-hidden-base-1.png
  src/components/input-group/daikin-input-group.visual.test.ts-snapshots/dark-TextArea-enabled-optional-error-visible-base-1.png
  src/components/input-group/daikin-input-group.visual.test.ts-snapshots/dark-TextArea-enabled-required-error-hidden-base-1.png
  src/components/input-group/daikin-input-group.visual.test.ts-snapshots/dark-TextArea-enabled-required-error-visible-base-1.png
  src/components/input-group/daikin-input-group.visual.test.ts-snapshots/dark-TextField-enabled-optional-error.png
  src/components/input-group/daikin-input-group.visual.test.ts-snapshots/dark-TextField-enabled-required-error.png
  src/components/input-group/daikin-input-group.visual.test.ts-snapshots/error-base-1.png
  src/components/input-group/daikin-input-group.visual.test.ts-snapshots/light-Dropdown-enabled-optional-error.png
  src/components/input-group/daikin-input-group.visual.test.ts-snapshots/light-Dropdown-enabled-required-error.png
  src/components/input-group/daikin-input-group.visual.test.ts-snapshots/light-RadioGroup-enabled-optional-error.png
  src/components/input-group/daikin-input-group.visual.test.ts-snapshots/light-RadioGroup-enabled-required-error.png
  src/components/input-group/daikin-input-group.visual.test.ts-snapshots/light-Select-enabled-optional-error.png
  src/components/input-group/daikin-input-group.visual.test.ts-snapshots/light-Select-enabled-required-error.png
  src/components/input-group/daikin-input-group.visual.test.ts-snapshots/light-TextArea-enabled-optional-error-hidden-base-1.png
  src/components/input-group/daikin-input-group.visual.test.ts-snapshots/light-TextArea-enabled-optional-error-visible-base-1.png
  src/components/input-group/daikin-input-group.visual.test.ts-snapshots/light-TextArea-enabled-required-error-hidden-base-1.png
  src/components/input-group/daikin-input-group.visual.test.ts-snapshots/light-TextArea-enabled-required-error-visible-base-1.png
  src/components/input-group/daikin-input-group.visual.test.ts-snapshots/light-TextField-enabled-optional-error.png
  src/components/input-group/daikin-input-group.visual.test.ts-snapshots/light-TextField-enabled-required-error.png
  src/components/progress-bar/daikin-progress-bar.visual.test.ts-snapshots/dark-error-large-exist-base-1.png
  src/components/progress-bar/daikin-progress-bar.visual.test.ts-snapshots/dark-error-large-none-base-1.png
  src/components/progress-bar/daikin-progress-bar.visual.test.ts-snapshots/dark-error-medium-exist-base-1.png
  src/components/progress-bar/daikin-progress-bar.visual.test.ts-snapshots/dark-error-medium-none-base-1.png
  src/components/progress-bar/daikin-progress-bar.visual.test.ts-snapshots/light-error-large-exist-base-1.png
  src/components/progress-bar/daikin-progress-bar.visual.test.ts-snapshots/light-error-large-none-base-1.png
  src/components/progress-bar/daikin-progress-bar.visual.test.ts-snapshots/light-error-medium-exist-base-1.png
  src/components/progress-bar/daikin-progress-bar.visual.test.ts-snapshots/light-error-medium-none-base-1.png
Labels: retouching
