Repository dsv-rp/DDS, pull requests merged in 2024-10, with the labels that each got.

#77 DDS-1524 Add component import guideline to documentation
  .changeset/khaki-radios-approve.md
  src/components/accordion-item/daikin-accordion-item.ts
  src/components/accordion/daikin-accordion.ts
  src/components/breadcrumb-item/daikin-breadcrumb-item.ts
  src/components/breadcrumb/daikin-breadcrumb.ts
  src/components/button/daikin-button.ts
  src/components/checkbox/daikin-checkbox.ts
  src/components/icon/daikin-icon.ts
  src/components/input-group/daikin-input-group.ts
  src/components/notification/daikin-notification.ts
  src/components/panel-switcher/daikin-panel-switcher.ts
  src/components/progress-bar/daikin-progress-bar.ts
  src/components/radio/daikin-radio.ts
  src/components/tab-group/daikin-tab-group.ts
  src/components/tab/daikin-tab.ts
  src/components/text-input/daikin-text-input.ts
  src/components/textarea/daikin-textarea.ts
  src/components/toggle/daikin-toggle.ts
  src/components/tooltip/daikin-tooltip.ts
Labels: documentation

#72 DDS-1385 [Progress Bar] Retouching
  .changeset/brave-foxes-exist.md
  icons/status-error.svg
  icons/status-negative.svg
  src/components/icon/icons.json
  src/components/input-group/daikin-input-group.ts
  src/components/progress-bar/daikin-progress-bar.ts
  src/components/progress-bar/daikin-progress-bar.visual.test.ts
  src/components/progress-bar/daikin-progress-bar.visual.test.ts-snapshots/completed-exist-base-1.png
  src/components/progress-bar/daikin-progress-bar.visual.test.ts-snapshots/completed-large-exist-base-1.png
  src/components/progress-bar/daikin-progress-bar.visual.test.ts-snapshots/completed-large-none-base-1.png
  src/components/progress-bar/daikin-progress-bar.visual.test.ts-snapshots/completed-medium-exist-base-1.png
  src/components/progress-bar/daikin-progress-bar.visual.test.ts-snapshots/completed-medium-none-base-1.png
  src/components/progress-bar/daikin-progress-bar.visual.test.ts-snapshots/completed-none-base-1.png
  src/components/progress-bar/daikin-progress-bar.visual.test.ts-snapshots/error-exist-base-1.png
  src/components/progress-bar/daikin-progress-bar.visual.test.ts-snapshots/error-large-exist-base-1.png
  src/components/progress-bar/daikin-progress-bar.visual.test.ts-snapshots/error-large-none-base-1.png
  src/components/progress-bar/daikin-progress-bar.visual.test.ts-snapshots/error-medium-exist-base-1.png
  src/components/progress-bar/daikin-progress-bar.visual.test.ts-snapshots/error-medium-none-base-1.png
  src/components/progress-bar/daikin-progress-bar.visual.test.ts-snapshots/error-none-base-1.png
  src/components/progress-bar/daikin-progress-bar.visual.test.ts-snapshots/indeterminate-exist-base-1.png
  src/components/progress-bar/daikin-progress-bar.visual.test.ts-snapshots/indeterminate-large-exist-base-1.png
  src/components/progress-bar/daikin-progress-bar.visual.test.ts-snapshots/indeterminate-large-none-base-1.png
  src/components/progress-bar/daikin-progress-bar.visual.test.ts-snapshots/indeterminate-medium-exist-base-1.png
  src/components/progress-bar/daikin-progress-bar.visual.test.ts-snapshots/indeterminate-medium-none-base-1.png
  src/components/progress-bar/daikin-progress-bar.visual.test.ts-snapshots/indeterminate-none-base-1.png
  src/components/progress-bar/daikin-progress-bar.visual.test.ts-snapshots/inprogress-exist-base-1.png
  src/components/progress-bar/daikin-progress-bar.visual.test.ts-snapshots/inprogress-large-exist-base-1.png
  src/components/progress-bar/daikin-progress-bar.visual.test.ts-snapshots/inprogress-large-none-base-1.png
  src/components/progress-bar/daikin-progress-bar.visual.test.ts-snapshots/inprogress-medium-exist-base-1.png
  src/components/progress-bar/daikin-progress-bar.visual.test.ts-snapshots/inprogress-medium-none-base-1.png
  src/components/progress-bar/daikin-progress-bar.visual.test.ts-snapshots/inprogress-none-base-1.png
  src/components/progress-bar/stories/common.ts
  src/components/progress-bar/stories/daikin-progress-bar.stories.ts
  src/components/progress-bar/stories/framework-wc.ts
Labels: waiting for design, retouching

#78 DDS-1301 [Toggle] Add `switch` role
  .changeset/tricky-stingrays-obey.md
  src/components/toggle/daikin-toggle.ts
  src/components/toggle/stories/daikin-toggle.stories.ts
Labels: bug

#69 DDS-1414 [Accordion] Retouching
  .changeset/hot-pumpkins-visit.md
  cspell-dictionary.txt
  icons/accordion-chevron-up.svg
  icons/chevron-down.svg
  icons/chevron-up.svg
  src/components/accordion-item/daikin-accordion-item.ts
  src/components/accordion-item/daikin-accordion-item.visual.test.ts
  src/components/accordion-item/daikin-accordion-item.visual.test.ts-snapshots/close-base-1.png
  src/components/accordion-item/daikin-accordion-item.visual.test.ts-snapshots/close-disabled-1.png
  src/components/accordion-item/daikin-accordion-item.visual.test.ts-snapshots/close-disabled-base-1.png
  src/components/accordion-item/daikin-accordion-item.visual.test.ts-snapshots/close-disabled-focus-1.png
  src/components/accordion-item/daikin-accordion-item.visual.test.ts-snapshots/close-disabled-hover-1.png
  src/components/accordion-item/daikin-accordion-item.visual.test.ts-snapshots/close-disabled-press-1.png
  src/components/accordion-item/daikin-accordion-item.visual.test.ts-snapshots/close-enabled-base-1.png
  src/components/accordion-item/daikin-accordion-item.visual.test.ts-snapshots/close-enabled-focus-1.png
  src/components/accordion-item/daikin-accordion-item.visual.test.ts-snapshots/close-enabled-hover-1.png
  src/components/accordion-item/daikin-accordion-item.visual.test.ts-snapshots/close-enabled-press-1.png
  src/components/accordion-item/daikin-accordion-item.visual.test.ts-snapshots/close-focus-1.png
  src/components/accordion-item/daikin-accordion-item.visual.test.ts-snapshots/close-hover-1.png
  src/components/accordion-item/daikin-accordion-item.visual.test.ts-snapshots/close-press-1.png
  src/components/accordion-item/daikin-accordion-item.visual.test.ts-snapshots/open-base-1.png
  src/components/accordion-item/daikin-accordion-item.visual.test.ts-snapshots/open-disabled-1.png
  src/components/accordion-item/daikin-accordion-item.visual.test.ts-snapshots/open-disabled-base-1.png
  src/components/accordion-item/daikin-accordion-item.visual.test.ts-snapshots/open-disabled-focus-1.png
  src/components/accordion-item/daikin-accordion-item.visual.test.ts-snapshots/open-disabled-hover-1.png
  src/components/accordion-item/daikin-accordion-item.visual.test.ts-snapshots/open-disabled-press-1.png
  src/components/accordion-item/daikin-accordion-item.visual.test.ts-snapshots/open-enabled-base-1.png
  src/components/accordion-item/daikin-accordion-item.visual.test.ts-snapshots/open-enabled-focus-1.png
  src/components/accordion-item/daikin-accordion-item.visual.test.ts-snapshots/open-enabled-hover-1.png
  src/components/accordion-item/daikin-accordion-item.visual.test.ts-snapshots/open-enabled-press-1.png
  src/components/accordion-item/daikin-accordion-item.visual.test.ts-snapshots/open-focus-1.png
  src/components/accordion-item/daikin-accordion-item.visual.test.ts-snapshots/open-hover-1.png
  src/components/accordion-item/daikin-accordion-item.visual.test.ts-snapshots/open-press-1.png
  src/components/accordion-item/stories/common.ts
  src/components/accordion-item/stories/daikin-accordion-item.stories.ts
  src/components/accordion-item/stories/framework-react.tsx
  src/components/accordion-item/stories/framework-wc.ts
  src/components/accordion/daikin-accordion.ts
  src/components/accordion/daikin-accordion.visual.test.ts-snapshots/base-1.png
  src/components/accordion/stories/daikin-accordion.stories.ts
  src/components/accordion/stories/framework-react.tsx
  src/components/accordion/stories/framework-wc.ts
  src/components/icon/icons.json
Labels: waiting for design, retouching

#75 DDS-1482 [Breadcrumb] fix breadcrumb accessibility
  .changeset/fresh-dolphins-trade.md
  eslint.config.js
  src/components/breadcrumb-item/daikin-breadcrumb-item.ts
  src/components/breadcrumb/daikin-breadcrumb.ts
  src/components/breadcrumb/stories/daikin-breadcrumb.stories.ts
Labels: bug

#74 DDS-1294 [Tooltip] Tooltip does not overflow parent element, Tooltip does not open even if trigger has focus
  .changeset/rude-pigs-hide.md
  cspell-dictionary.txt
  src/components/button/stories/framework-react.tsx
  src/components/tooltip/daikin-tooltip.ts
  src/components/tooltip/daikin-tooltip.visual.test.ts
  src/components/tooltip/daikin-tooltip.visual.test.ts-snapshots/attribute-base-1.png
  src/components/tooltip/daikin-tooltip.visual.test.ts-snapshots/dark-bottom-center-1.png
  src/components/tooltip/daikin-tooltip.visual.test.ts-snapshots/dark-bottom-leftTop-1.png
  src/components/tooltip/daikin-tooltip.visual.test.ts-snapshots/dark-bottom-rightBottom-1.png
  src/components/tooltip/daikin-tooltip.visual.test.ts-snapshots/dark-left-center-1.png
  src/components/tooltip/daikin-tooltip.visual.test.ts-snapshots/dark-left-leftTop-1.png
  src/components/tooltip/daikin-tooltip.visual.test.ts-snapshots/dark-left-rightBottom-1.png
  src/components/tooltip/daikin-tooltip.visual.test.ts-snapshots/dark-newline-1.png
  src/components/tooltip/daikin-tooltip.visual.test.ts-snapshots/dark-right-center-1.png
  src/components/tooltip/daikin-tooltip.visual.test.ts-snapshots/dark-right-leftTop-1.png
  src/components/tooltip/daikin-tooltip.visual.test.ts-snapshots/dark-right-rightBottom-1.png
  src/components/tooltip/daikin-tooltip.visual.test.ts-snapshots/dark-top-center-1.png
  src/components/tooltip/daikin-tooltip.visual.test.ts-snapshots/dark-top-leftTop-1.png
  src/components/tooltip/daikin-tooltip.visual.test.ts-snapshots/dark-top-rightBottom-1.png
  src/components/tooltip/daikin-tooltip.visual.test.ts-snapshots/light-bottom-center-1.png
  src/components/tooltip/daikin-tooltip.visual.test.ts-snapshots/light-bottom-leftTop-1.png
  src/components/tooltip/daikin-tooltip.visual.test.ts-snapshots/light-bottom-rightBottom-1.png
  src/components/tooltip/daikin-tooltip.visual.test.ts-snapshots/light-left-center-1.png
  src/components/tooltip/daikin-tooltip.visual.test.ts-snapshots/light-left-leftTop-1.png
  src/components/tooltip/daikin-tooltip.visual.test.ts-snapshots/light-left-rightBottom-1.png
  src/components/tooltip/daikin-tooltip.visual.test.ts-snapshots/light-newline-1.png
  src/components/tooltip/daikin-tooltip.visual.test.ts-snapshots/light-right-center-1.png
  src/components/tooltip/daikin-tooltip.visual.test.ts-snapshots/light-right-leftTop-1.png
  src/components/tooltip/daikin-tooltip.visual.test.ts-snapshots/light-right-rightBottom-1.png
  src/components/tooltip/daikin-tooltip.visual.test.ts-snapshots/light-top-center-1.png
  src/components/tooltip/daikin-tooltip.visual.test.ts-snapshots/light-top-leftTop-1.png
  src/components/tooltip/daikin-tooltip.visual.test.ts-snapshots/light-top-rightBottom-1.png
  src/components/tooltip/daikin-tooltip.visual.test.ts-snapshots/slot-base-1.png
  src/components/tooltip/stories/common.ts
  src/components/tooltip/stories/daikin-tooltip.stories.ts
  src/components/tooltip/stories/framework-react.tsx
  src/components/tooltip/stories/framework-wc.ts
  src/utils/reDispatch.ts
Labels: bug
