Repository dsv-rp/DDS, pull requests merged in 2025-01, with the labels that each got.

#113 DDS-1679 [Checkbox] [Radio Button] Fix clicking the label triggers click event twice
  .changeset/funny-rings-live.md
  src/components/checkbox/daikin-checkbox.ts
  src/components/checkbox/stories/daikin-checkbox.stories.ts
  src/components/radio/daikin-radio.ts
  src/components/radio/stories/daikin-radio.stories.ts
Labels: bug

#109 DDS-1296 [Carousel] Add Carousel Component
  .changeset/itchy-seahorses-arrive.md
  src/components/carousel-item/daikin-carousel-item.ts
  src/components/carousel-item/daikin-carousel-item.visual.test.ts
  src/components/carousel-item/daikin-carousel-item.visual.test.ts-snapshots/base-1.png
  src/components/carousel-item/index.ts
  src/components/carousel-item/stories/common.ts
  src/components/carousel-item/stories/daikin-carousel-item.stories.ts
  src/components/carousel-item/stories/framework-react.tsx
  src/components/carousel-item/stories/framework-wc.ts
  src/components/carousel/daikin-carousel.ts
  src/components/carousel/daikin-carousel.visual.test.ts
  src/components/carousel/daikin-carousel.visual.test.ts-snapshots/dark-first-base-1.png
  src/components/carousel/daikin-carousel.visual.test.ts-snapshots/dark-last-base-1.png
  src/components/carousel/daikin-carousel.visual.test.ts-snapshots/dark-second-base-1.png
  src/components/carousel/daikin-carousel.visual.test.ts-snapshots/light-first-base-1.png
  src/components/carousel/daikin-carousel.visual.test.ts-snapshots/light-last-base-1.png
  src/components/carousel/daikin-carousel.visual.test.ts-snapshots/light-second-base-1.png
  src/components/carousel/index.ts
  src/components/carousel/stories/common.ts
  src/components/carousel/stories/daikin-carousel.stories.ts
  src/components/carousel/stories/framework-react.tsx
  src/components/carousel/stories/framework-wc.ts
  src/components/index.ts
Labels: new component

#115 [Progress Indicator] Update appearance
  .changeset/sixty-garlics-wink.md
  icons/status-success.svg
  src/components/icon/icons.json
  src/components/progress-indicator-item/daikin-progress-indicator-item.ts
  src/components/progress-indicator-item/daikin-progress-indicator-item.visual.test.ts-snapshots/dark-finished-base-1.png
  src/components/progress-indicator-item/daikin-progress-indicator-item.visual.test.ts-snapshots/dark-inprogress-base-1.png
  src/components/progress-indicator-item/daikin-progress-indicator-item.visual.test.ts-snapshots/dark-unfinished-base-1.png
  src/components/progress-indicator-item/daikin-progress-indicator-item.visual.test.ts-snapshots/light-finished-base-1.png
  src/components/progress-indicator-item/daikin-progress-indicator-item.visual.test.ts-snapshots/light-inprogress-base-1.png
  src/components/progress-indicator-item/daikin-progress-indicator-item.visual.test.ts-snapshots/light-unfinished-base-1.png
  src/components/progress-indicator/daikin-progress-indicator.visual.test.ts-snapshots/dark-base-1.png
  src/components/progress-indicator/daikin-progress-indicator.visual.test.ts-snapshots/light-base-1.png
Labels: retouching

#118 [Progress Bar] Update appearance
  .changeset/famous-carrots-lie.md
  src/components/progress-bar/daikin-progress-bar.ts
  src/components/progress-bar/daikin-progress-bar.visual.test.ts-snapshots/dark-completed-large-exist-base-1.png
  src/components/progress-bar/daikin-progress-bar.visual.test.ts-snapshots/dark-completed-large-none-base-1.png
  src/components/progress-bar/daikin-progress-bar.visual.test.ts-snapshots/dark-completed-medium-exist-base-1.png
  src/components/progress-bar/daikin-progress-bar.visual.test.ts-snapshots/dark-completed-medium-none-base-1.png
  src/components/progress-bar/daikin-progress-bar.visual.test.ts-snapshots/dark-error-large-exist-base-1.png
  src/components/progress-bar/daikin-progress-bar.visual.test.ts-snapshots/dark-error-large-none-base-1.png
  src/components/progress-bar/daikin-progress-bar.visual.test.ts-snapshots/dark-error-medium-exist-base-1.png
  src/components/progress-bar/daikin-progress-bar.visual.test.ts-snapshots/dark-error-medium-none-base-1.png
  src/components/progress-bar/daikin-progress-bar.visual.test.ts-snapshots/dark-indeterminate-large-exist-base-1.png
  src/components/progress-bar/daikin-progress-bar.visual.test.ts-snapshots/dark-indeterminate-large-none-base-1.png
  src/components/progress-bar/daikin-progress-bar.visual.test.ts-snapshots/dark-indeterminate-medium-exist-base-1.png
  src/components/progress-bar/daikin-progress-bar.visual.test.ts-snapshots/dark-indeterminate-medium-none-base-1.png
  src/components/progress-bar/daikin-progress-bar.visual.test.ts-snapshots/dark-inprogress-large-exist-base-1.png
  src/components/progress-bar/daikin-progress-bar.visual.test.ts-snapshots/dark-inprogress-large-none-base-1.png
  src/components/progress-bar/daikin-progress-bar.visual.test.ts-snapshots/dark-inprogress-medium-exist-base-1.png
  src/components/progress-bar/daikin-progress-bar.visual.test.ts-snapshots/dark-inprogress-medium-none-base-1.png
  src/components/progress-bar/daikin-progress-bar.visual.test.ts-snapshots/light-completed-large-exist-base-1.png
  src/components/progress-bar/daikin-progress-bar.visual.test.ts-snapshots/light-completed-large-none-base-1.png
  src/components/progress-bar/daikin-progress-bar.visual.test.ts-snapshots/light-completed-medium-exist-base-1.png
  src/components/progress-bar/daikin-progress-bar.visual.test.ts-snapshots/light-completed-medium-none-base-1.png
  src/components/progress-bar/daikin-progress-bar.visual.test.ts-snapshots/light-error-large-exist-base-1.png
  src/components/progress-bar/daikin-progress-bar.visual.test.ts-snapshots/light-error-large-none-base-1.png
  src/components/progress-bar/daikin-progress-bar.visual.test.ts-snapshots/light-error-medium-exist-base-1.png
  src/components/progress-bar/daikin-progress-bar.visual.test.ts-snapshots/light-error-medium-none-base-1.png
  src/components/progress-bar/daikin-progress-bar.visual.test.ts-snapshots/light-indeterminate-large-exist-base-1.png
  src/components/progress-bar/daikin-progress-bar.visual.test.ts-snapshots/light-indeterminate-large-none-base-1.png
  src/components/progress-bar/daikin-progress-bar.visual.test.ts-snapshots/light-indeterminate-medium-exist-base-1.png
  src/components/progress-bar/daikin-progress-bar.visual.test.ts-snapshots/light-indeterminate-medium-none-base-1.png
  src/components/progress-bar/daikin-progress-bar.visual.test.ts-snapshots/light-inprogress-large-exist-base-1.png
  src/components/progress-bar/daikin-progress-bar.visual.test.ts-snapshots/light-inprogress-large-none-base-1.png
  src/components/progress-bar/daikin-progress-bar.visual.test.ts-snapshots/light-inprogress-medium-exist-base-1.png
  src/components/progress-bar/daikin-progress-bar.visual.test.ts-snapshots/light-inprogress-medium-none-base-1.png
Labels: retouching

#116 DDS-915 [Pagination] Retouching
  .changeset/curly-chicken-clap.md
  src/components/pagination/daikin-pagination.ts
  src/components/pagination/daikin-pagination.visual.test.ts-snapshots/dark-default-base-1.png
  src/components/pagination/daikin-pagination.visual.test.ts-snapshots/dark-default-page-focus-1.png
  src/components/pagination/daikin-pagination.visual.test.ts-snapshots/dark-default-page-hover-1.png
  src/components/pagination/daikin-pagination.visual.test.ts-snapshots/dark-default-page-press-1.png
  src/components/pagination/daikin-pagination.visual.test.ts-snapshots/dark-ellipsis-base-1.png
  src/components/pagination/daikin-pagination.visual.test.ts-snapshots/dark-ellipsis-focus-dropdown-1.png
  src/components/pagination/daikin-pagination.visual.test.ts-snapshots/dark-ellipsis-hover-dropdown-1.png
  src/components/pagination/daikin-pagination.visual.test.ts-snapshots/dark-left-chevron-focus-1.png
  src/components/pagination/daikin-pagination.visual.test.ts-snapshots/dark-left-chevron-hover-1.png
  src/components/pagination/daikin-pagination.visual.test.ts-snapshots/dark-left-chevron-press-1.png
  src/components/pagination/daikin-pagination.visual.test.ts-snapshots/dark-right-chevron-focus-1.png
  src/components/pagination/daikin-pagination.visual.test.ts-snapshots/dark-right-chevron-hover-1.png
  src/components/pagination/daikin-pagination.visual.test.ts-snapshots/dark-right-chevron-press-1.png
  src/components/pagination/daikin-pagination.visual.test.ts-snapshots/dark-selected-page-focus-1.png
  src/components/pagination/daikin-pagination.visual.test.ts-snapshots/dark-selected-page-hover-1.png
  src/components/pagination/daikin-pagination.visual.test.ts-snapshots/dark-selected-page-press-1.png
  src/components/pagination/daikin-pagination.visual.test.ts-snapshots/light-default-base-1.png
  src/components/pagination/daikin-pagination.visual.test.ts-snapshots/light-default-page-focus-1.png
  src/components/pagination/daikin-pagination.visual.test.ts-snapshots/light-default-page-hover-1.png
  src/components/pagination/daikin-pagination.visual.test.ts-snapshots/light-default-page-press-1.png
  src/components/pagination/daikin-pagination.visual.test.ts-snapshots/light-ellipsis-base-1.png
  src/components/pagination/daikin-pagination.visual.test.ts-snapshots/light-ellipsis-focus-dropdown-1.png
  src/components/pagination/daikin-pagination.visual.test.ts-snapshots/light-ellipsis-hover-dropdown-1.png
  src/components/pagination/daikin-pagination.visual.test.ts-snapshots/light-left-chevron-focus-1.png
  src/components/pagination/daikin-pagination.visual.test.ts-snapshots/light-left-chevron-hover-1.png
  src/components/pagination/daikin-pagination.visual.test.ts-snapshots/light-left-chevron-press-1.png
  src/components/pagination/daikin-pagination.visual.test.ts-snapshots/light-right-chevron-focus-1.png
  src/components/pagination/daikin-pagination.visual.test.ts-snapshots/light-right-chevron-hover-1.png
  src/components/pagination/daikin-pagination.visual.test.ts-snapshots/light-right-chevron-press-1.png
  src/components/pagination/daikin-pagination.visual.test.ts-snapshots/light-selected-page-focus-1.png
  src/components/pagination/daikin-pagination.visual.test.ts-snapshots/light-selected-page-hover-1.png
  src/components/pagination/daikin-pagination.visual.test.ts-snapshots/light-selected-page-press-1.png
Labels: retouching

#117 [Accordion] Support exclusive accordion
  .changeset/nice-coats-kneel.md
  src/components/accordion-item/daikin-accordion-item.ts
  src/components/accordion-item/stories/common.ts
  src/components/accordion-item/stories/daikin-accordion-item.stories.ts
  src/components/accordion-item/stories/framework-react.tsx
  src/components/accordion-item/stories/framework-wc.ts
  src/components/accordion/daikin-accordion.ts
  src/components/accordion/daikin-accordion.visual.test.ts
  src/components/accordion/stories/common.ts
  src/components/accordion/stories/daikin-accordion.stories.ts
  src/components/accordion/stories/framework-react.tsx
  src/components/accordion/stories/framework-wc.ts
Labels: enhancement
